### ISSUE TITLE
Error publishing WHIP to Simple WHIP Server

### ISSUE THREAD

**Issue by lminiero** [agonza1/free-whip#1]
Hi,

thanks for sharing a new WHIP client implementation! As part of the [IETF 112 Hackathon](https://www.ietf.org/how/runningcode/hackathons/112-hackathon/), I'm tinkering with other WHIP implementations I've become aware of, so I wanted to test yours too. The README says this was tested with my WHIP server (and so Janus), but I can't get it to work for some reason.

When I try to contact the WHIP endoint with your client this is what I get:

```
[lminiero@lminiero whip-cli-client]$ python publish.py http://localhost:7080/whip/endpoint/test
ICE connection state is closed
Traceback (most recent call last):
  File "/home/lminiero/Work/code/services/whip/free-whip/whip-cli-client/publish.py", line 142, in <module>
    loop.run_until_complete(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/lminiero/Work/code/services/whip/free-whip/whip-cli-client/publish.py", line 104, in run
    await publish(session=session, player=player)
  File "/home/lminiero/Work/code/services/whip/free-whip/whip-cli-client/publish.py", line 88, in publish
    await pc.setLocalDescription(offer)
  File "/home/lminiero/.local/lib/python3.9/site-packages/aiortc/rtcpeerconnection.py", line 771, in setLocalDescription
    await self.__gather()
  File "/home/lminiero/.local/lib/python3.9/site-packages/aiortc/rtcpeerconnection.py", line 1011, in __gather
    await asyncio.gather(*coros)
  File "/home/lminiero/.local/lib/python3.9/site-packages/aiortc/rtcicetransport.py", line 198, in gather
    await self._connection.gather_candidates()
  File "/home/lminiero/.local/lib/python3.9/site-packages/aioice/ice.py", line 416, in gather_candidates
    for candidates in await asyncio.gather(*coros):
  File "/home/lminiero/.local/lib/python3.9/site-packages/aioice/ice.py", line 886, in get_component_candidates
    _, protocol = await turn.create_turn_endpoint(
  File "/home/lminiero/.local/lib/python3.9/site-packages/aioice/turn.py", line 380, in create_turn_endpoint
    _, inner_protocol = await loop.create_datagram_endpoint(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1296, in create_datagram_endpoint
    infos = await self._ensure_resolved(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Initially I thought it might be because of the fact I hadn't started Janus in ICE Lite mode (which shouldn't be needed even with aiortc, though, as we use it as part of our automated tests and it works fine with full ICE too), but even enabling ICE Lite I'm still getting the same error. This is all done locally so not sure where the `Name or service not known` is coming from.

Any hint on what may be going wrong? Thanks!

**Comment by lminiero** [comment]
Looks like this is the cause:

https://github.com/agonza1/free-whip/blob/main/whip-cli-client/publish.py#L60

I'm not running this on docker, so this TURN server doesn't exist, hence the error. Not sure if the code should have a flag/argument to check whether it's running in docker or not? Anyway, removing the TURN server and only leaving the STUN server there goes forward, but fails somewhere else, so I'll look into this now.

**Comment by lminiero** [comment]
Ok, I found out what the other issues where, and got WebRTC to work :partying_face: 

What I was trying was:

    python publish.py http://localhost:7080/whip/endpoint/test

which didn't work because the client was turning the endpoint in a link like this:

    http://localhost:7080/whip/endpoint/test/whip/endpoint/1234

I guess it has a hardcoded `/whip/endpoint` base, and a hardcoded `1234` as endpoint. Doing this instead:

    python publish.py --room test http://localhost:7080/

failed because it's expecting the endpoint ID to be numeric, which is not required at all in the Simple WHIP Server: the endpoint ID can be any alphanumeric string, and the VideoRoom room mapping is done using a different variable. Anyway, creating a WHIP endpoint with a numeric ID got it to work.

My feedback would be not to expect the WHIP server to use `/whip/endpoint` as base, as that will often not be true; numeric ID for endpoint is also not suggested. Thanks for working on this anyway, it's always exciting to see interop tests that work!

**Comment by agonza1** [comment]
Hi @lminiero 
You were quick figuring it out! I totally agree with your points:
- It might not be running in docker so it is something I can add a flag to
- Allow passing the full URL without assuming a specific path would be a better approach

I will fix those things soon. I appreciate you took the time to play around with it!
